// <auto-generated />
using System;
using Forum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230605103905_CreateAndSeedDbContext")]
    partial class CreateAndSeedDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74493667-b935-4269-8ed5-31b7a9b3bfc9"),
                            Content = "What is ASP.NET?",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("079d13a9-601a-46d4-8025-80430715d2c9"),
                            Content = "ASP.NET is an open source web framework, created by Microsoft, for building modern web apps and services with .NET.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("77d3bdec-4936-48de-bb6e-2a86d578d67f"),
                            Content = "ASP.NET is cross platform and runs on Windows, Linux, macOS, and Docker.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
